config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  
  get 'welcome/index'

  root 'welcome#index'
  
  resources 'chats' do
    resources :messages
  end
  
  get '*path' => redirect('/')
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  has_many :messages
  has_many :private_users
  
  validates :title, presence: true, length: {minimum: 5, maximum: 30}
    
  # Chat.private_chat
  accepts_nested_attributes_for :private_users, :reject_if => :all_blank, :allow_destroy => true
  
  def admin?
    self == User.first
  end
  
  def owner
  end
  
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :chat
    belongs_to :user
end

app/models/private_user.rb
class PrivateUser < ActiveRecord::Base
    belongs_to :chat
end
    

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :chats
  has_many :messages
  
  scope :online, lambda{ where("updated_at > ?", 10.minutes.ago) }
  
  def admin?
    self == User.first
  end
  
  def online?
    updated_at > 10.minutes.ago
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	after_filter :user_activity
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end
	
	private
	
	
	def user_activity
  	current_user.try :touch
	end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :find_chat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  #before_filter :assign_user, only: [ :new ]
  
  def index
    @chats = Chat.all.order("created_at DESC")
  end

  def show
    if @chat.private?
      if @chat.private_users.find_by_email(current_user.email) != nil || current_user.admin? || @chat.user_id == current_user.id
      #if @chat.private_users.all? {|email| @chat.private_users.include?(current_user.email)} == true
        @messages = Message.where(chat_id: @chat)
      else
       redirect_to chats_path, notice: "You must be invited to join this chat room"
      end
    end
    if @chat.public?
      @messages = Message.where(chat_id: @chat)
    end
  end
  
  def new
  	@chat = current_user.chats.build
  end
  
  def create
  	@chat = current_user.chats.build chat_params
  
  	if @chat.save
  		redirect_to @chat, notice: "Hellz yeah! Your chat was successfully saved!"
  	else
  		render 'new', notice: "Oh no! I was unable to save your chat."
  	end
  end
  
  def edit
  end
  
  def update
    if @chat.update(chat_params)
      redirect_to @chat, notice: "Your chat was updates successfully"
    else
      render 'edit'
    end
  end
  
  def destroy
    @chat.destroy
    redirect_to chats_path, notice: "You Destroy Chat"
  end
  
private

  def chat_params
  	params.require(:chat).permit(:title, :private, :privatemail, private_users_attributes: [:id, :email, :_destroy])
  end
  
  def find_chat
  	@chat = Chat.find(params[:id])
  end
  
  def assign_user
    resource.user = current_user
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    
    
	def create
		@chat = Chat.find(params[:chat_id])
		@message = Message.create(params[:message].permit(:content))
		@message.user_id = current_user.id
		@message.chat_id = @chat.id
		
		respond_to do |format|
			if @message.save
				format.js do
					PrivatePub.publish_to "/chats/#{@chat.id}/messages", message: @message.to_json
				#redirect_to chat_path(@chat), notice: "Комментарий добавлен успешно"
					render nothing: true
				end
				#format.html {redirect_to chat_path(@chat), notice: "Комментарий добавлен успешно"}
			else
				format.js do
					PrivatePub.publish_to "/chats/#{@chat.id}/messages", errors: @messages.errors.full_messages
					render nothing: true
					#render 'new'
				end
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_user, only: [:edit, :update, :show]

	def index

	end

	def show
		#@recipes = current_chef.recipes.find(params[:id])
		@chat = Chat.find(params[:id])
		@chats = Chat.all.order("created_at DESC")
	end
	
	private
	
	def set_user
		@user = User.find(params[:id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 70 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
	
	def link_to_in_li(body, url)
    active = "active" if current_page?(url)
    content_tag :li, class: active do
      link_to body, url
    end
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/_chats.html.erb
<div id="comments" data-chat-id="<%= @chat.id %>" >
  <% @chat.messages.each do |message| %>
    <div class="comment">
      <div id="avatar">
        <%= link_to gravatar_for(message.user, size: 70) %>
      </div>
      <div class="message">
        <h5 class="username">User Name: <%= message.user.name %></h5>
        <p class=content><%= message.content %></p>
        <span class="quiet"><small>created: <%= time_ago_in_words(message.created_at) %> ago</small></span>
      </div>
    </div>
      
  <% end %>
</div>

app/views/chats/_private_user_fields.html.erb
<div class="nested-fields">
  <div class="form-group f-row">
    <div class="large"><%= f.email_field :email, :placeholder => "Email to add private user" %>
    
    <%= link_to_remove_association "-", f, class: "remove button" %></div>
  </div>
</div>

app/views/chats/edit.html.erb
<h1 id="page_title">Edit Chat: <%= @chat.title %></h1>

<div class="skinny_wrapper wrapper_padding">
 <%= form_for @chat do |f| %>
  	<% if @chat.errors.any? %>
  		<h2><%= pluralize(@chat.errors.count, "error") %> prevented this post from saving:</h2>
  		<ul>
  			<% @chat.errors.full_messages.each do |msg| %>
  				<li><%= msg %></li>
  			<% end %>
  		</ul>
  	<% end %>
  
  	<%= f.label :title %><br>
  	<%= f.text_field :title %>
  
    <%= f.check_box :private, {}, true, false %>
    <%= f.label :private, "Private Chat" %>

    <br>
    
    <%= f.check_box :public, {}, true, false %>
    <%= f.label :public, "Public Chat" %>
    
    <br>
    <br>
  	
  	<%= f.fields_for :private_users do |chat| %>
	    <%= render 'private_user_fields', f: chat %>
  	<% end %>
  	<div class="f-row full">
  		<%= link_to_add_association 'Add private user', f, :private_users, class: "button" %>
  	</div>
  
  	<br>
  	<br>
  	
  	<%= f.submit %>
  
  <% end %>
</div>

app/views/chats/index.html.erb
<div class="wrapper clearfix">
	<div class="col-1 homepage_content">
		
		<h1 id="page_title">All Chats</h1>
		<div class="chats_rooms">
      <% @chats.each do |chat| %>
        <ul>
          <br>
          <li><%= link_to chat.title, chat_path(chat), class: "button" %></li>
        </ul>
      <% end %>
    </div>

	</div>
	<div class="col-2 homepage_content">
	  <div class="chat_rooms">
  		<h2>Chat Rooms</h2>
  		<hr>
  		<ul>
        <li>Чебурашка</li>
        <li>Крокодил Гена</li>
        <li>Шапокляк</li>
        <li>Крыса Лариса</li>
      </ul>
    </div>
    <div class="user_online">
  		<h2>User Online</h2>
  		<hr>
  		<ul>
        <li>Darelvc</li>
        <li>Cadaverzian</li>
        <li>Millerd</li>
        <li>Nadegda</li>
      </ul>
    </div>
	</div>
</div>

app/views/chats/new.html.erb
<h1 id="page_title">Create new Chat</h1>

<div class="skinny_wrapper wrapper_padding">
 <%= form_for @chat do |f| %>
  	<% if @chat.errors.any? %>
  		<h2><%= pluralize(@chat.errors.count, "error") %> prevented this post from saving:</h2>
  		<ul>
  			<% @chat.errors.full_messages.each do |msg| %>
  				<li><%= msg %></li>
  			<% end %>
  		</ul>
  	<% end %>
  
  	<%= f.label :title %><br>
  	<%= f.text_field :title %>
  	
  	<div class="private_public">
      	<%= f.check_box :private, {}, true, false %>
        <%= f.label :private, "Private Chat" %>
    
        <br>
        
        <%= f.check_box :public, {}, true, false %>
        <%= f.label :public, "Public Chat" %>
        
        <br>
        <br>
  	</div>
  	
  	<%= f.fields_for :private_users do |chat| %>
		<%= render 'private_user_fields', f: chat %>
	<% end %>
	
	<div class="f-row full">
		<%= link_to_add_association 'Add private user', f, :private_users, class: "button" %>
	</div>
		
    <br>
  	<br>
  
  	<%= f.submit %>
  
  <% end %>
</div>

app/views/chats/show.html.erb
<div class="wrapper clearfix">
	<div class="col-1 homepage_content">
		
    <h1 id="page_title"><%= @chat.title %></h1>
    
      <%= render "chats/chats" %>
  
      <%= render "messages/form" %>
       
      <%= subscribe_to "/chats/#{@chat.id}/messages" %>
    
    <% if user_signed_in? && @chat.user_id == current_user.id || @chat.admin? %>
      <div id="admin_links">
        <%= link_to "Edit chat", edit_chat_path(@chat) %>
        <%= link_to "Close chat", chat_path(@chat), method: :delete, data: { confirm: "Are you sure?"} %>
      </div>
    <% end %>  
	</div>
	<div class="col-2 homepage_content">
	  <div class="chat_rooms">
  		<h2>Chat Rooms</h2>
  		<hr>
  		<ul>
        <li>Чебурашка</li>
        <li>Крокодил Гена</li>
        <li>Шапокляк</li>
        <li>Крыса Лариса</li>
      </ul>
    </div>
    <div class="user_online">
  		<h2>User Online</h2>
  		<hr>
  		<ul>
        <li>Darelvc</li>
        <li>Cadavercian</li>
        <li>Millerd</li>
        <li>Nadegda</li>
      </ul>
    </div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer id="main_footer">
	<p class="copyright">&copy;2016 Oleg Bloshenkin Chat App</p>
	<nav>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-vk"></i></i></a>
		<a href="#"><i class="fa fa-github"></i></a>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="clearfix" id="main_navigation">
  <%= link_to 'Demo Chat APP', root_path, class: "name" %>
	<nav>
		<%= link_to 'Home', root_path %>
		<%= link_to 'Chat rooms', chats_path %>
		<%  if user_signed_in? %>
		  <%= link_to 'New Chat', new_chat_path %>
		  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
		<% else %>
		  <%= link_to 'Login', new_user_session_path %>
		<% end %>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat app</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  
  <% if alert %>
	<div id="notice_wrapper">
		<p class="alert"><%= alert %></p>	
	</div>
  <% elsif notice %>
  	<div id="notice_wrapper">
  		<p class="notice"><%= notice %></p>		
  	</div>
  <% end %>
  
<%= yield %>
  <%= render 'layouts/footer' %>

  <script>
  	$(document).ready(function() {
  		setTimeout(function() {
  			$('#notice_wrapper').fadeOut("slow", function() {
  				$this.remove();
  			});
  		}, 2500 );
  	});
  </script>
</body>
</html>

app/views/messages/__form.html.1.erb
<%= simple_form_for([@chat, @chat.messages.build]), remote: true, data: {type: json} do |f| %>
	<%= f.input :content, label: "Reply to thread" %>
	<%= f.button :submit, class: "button" %>
<% end %>


def private_chat
    if @chat.private? == true
      @chat = @chat.privatemail.split(", ").uniq
      if @chat.all? {|email| @chat.include?(current_user.email)} == true
        @chat = Chat.find(params[:id])
      else
        redirect_to chats_path, notice: "You must be invited to this chat room"
      end
    else
      redirect_to chats_path, notice: "You must be invited to this chat room"
    end
  end

app/views/messages/_form.html.erb
<%= form_for [@chat, @chat.messages.build], remote: true, data: {type: :json} do |f| %>
  
    <div class="field">
      <%= f.label :content, "Reply to thread" %><br />
      <%= f.text_area :content %>
    </div>
    
    <div class="actions">
      <%= f.submit "Create", class: "button" %>
    </div>
    
    <br>
    
<% end %>

app/views/messages/create.js.erb
$('#messages').html('<%= j render 'chats/messages' %>');
$('.new_message #message_content').val('');

app/views/users/show.html.erb
<h1 id="page_title">User page: <%= @user.name %></h1>

<div class="skinny_wrapper wrapper_padding">
	<div class="show_avatar center">
		<%= gravatar_for @user, size: 200 %>
		<hr>
	</div>
	
	<h3 class="center"><%= @user.email %></h3>
	
	<p>Send a message: <%= @user.messages.count %></p>
	<p>Active Created Chat: <%= @user.chats.count %></p>
	
	<hr>
	
	<h3 class="center">All Chats by User: <%= @user.name %> </h3>
	
	<hr>
	
	<div class="chats_rooms">
  	<% @user.chats.each do |chat| %>
  	  <% if chat.private? %>
  	    <ul>
          <br>
          <li><%= link_to chat.title, chat_path(chat), class: "button button_private" %></li>
        </ul>
      <% else %>
        <ul>
          <br>
          <li><%= link_to chat.title, chat_path(chat), class: "button" %></li>
        </ul>
      <% end %>
    <% end %>
  </div>
  
  
</div>

app/views/welcome/index.html.erb
<div class="wrapper clearfix">
	<div class="col-1 homepage_content">
		
		<div class="welcome_content">
  		<h1>Welcome to my demo chat app</h1>
      <p>Hello, my name is Oleg Bloshenkin, I created this chat app for my test project on Ruby on Rails</p>
      
      <p>First, you must register or login to start communicating in this chat</p>
      
      <%= link_to "Sign up", new_user_registration_path, class: "button" %>
      <%= link_to "Login", new_user_session_path, class: "button" %>
		</div>
	</div>
	<div class="col-2 homepage_content">
	  <div class="chat_rooms">
  		<h2>Chat Rooms</h2>
  		<hr>
  		<ul>
        <li>Чебурашка</li>
        <li>Крокодил Гена</li>
        <li>Шапокляк</li>
        <li>Крыса Лариса</li>
      </ul>
    </div>
    <div class="user_online">
  		<h2>User Online</h2>
  		<hr>
  		<ul>
        <li>Darelvc</li>
        <li>Cadaverzian</li>
        <li>Millerd</li>
        <li>Nadegda</li>
      </ul>
    </div>
	</div>
</div>